**Resolver     utilizando otro     software el     problema     planteado anteriormente**

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('datos.csv')

In [4]:
df

   Casos  th  norte  °API     S    RFC  APUESTA  mic
0      1  24   1200    18  1.20  0.021  347.750    1
1      2  18   1300    23  4.92  0.068  159.040    0
2      3  19   1300    22  4.28  0.059  169.670    0
3      4  24   1200    14  0.52  0.020  343.380    1
4      5  18   1200    24  1.50  0.062  159.470    0
5      6  24   1200    20  0.73  0.021  362.156    1
6      7  24   1300    18  0.94  0.022  235.800    1
7      8  18   1200    15  1.28  0.062  159.880    0
8      9  24   1400    23  0.57  0.023  252.240    1
9     10  18   1300    17  4.38  0.070  158.320    0